
package client;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;

import java.util.Vector;

import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author Galutvo
 */
public class DialogInsert3s extends JDialog {
    private int icusnum=-1;
    private int clinum=-1;
    private int reasonflag;
    private String cusF;
    private String cusI;
    private String cusO;
    
    private String ikeynum;
    private String regdate;
    private String cliname;
    private String post;
    private String usbtype; 
    private String usbid;
    private String usbnum;
    private String usbactnum;
    private String usbactdate;
    private String otptype;
    private String otpid;
    private String otpnum;
    private String otpsum;
    private String distnum;
    private String distdate;
    

    /** Creates new form DialogInsert3s */
    public DialogInsert3s(java.awt.Dialog parent, String title, boolean modal, int icusnum, String clinum, int reason) {               
        super(parent, title, modal);        
        reasonflag=reason;//reason = 1 для linkdata, 2 для linkdataotp
        this.icusnum=icusnum;
        this.clinum=Integer.parseInt(clinum);        
        initComponents();                
        try {
            GetCusFIO(clinum);
            this.refilltable(this.jTable1);            
        } catch (SQLException e) {
        }
        this.FillFormDataLocal();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ранее выданные ПО и оборудование");
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event){
                if(jTable1.getSelectedRow() != -1){
                    FillFormData();
                }
            }});

            jButton1.setText("Закрыть");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jButton2.setText("Сохранить");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Установочный дистрибутив"));
            jPanel1.setMaximumSize(new java.awt.Dimension(169, 139));
            jPanel1.setMinimumSize(new java.awt.Dimension(169, 139));

            jLabel1.setText("Учетный номер:");

            jLabel2.setText("Дата выдачи:");

            jTextField4.setText("jTextField4");

            jTextField5.setText("jTextField5");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addComponent(jTextField5)))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(62, Short.MAX_VALUE))
            );

            jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("USB-токен / НЭК (носитель)"));
            jPanel2.setMaximumSize(new java.awt.Dimension(188, 139));
            jPanel2.setMinimumSize(new java.awt.Dimension(188, 139));

            jLabel3.setText("Тип устройства:");

            jLabel4.setText("Заводской номер:");

            jLabel5.setText("Дата выдачи:");

            jLabel6.setText("Учетный номер:");

            jTextField6.setText("jTextField6");

            jTextField7.setText("jTextField6");

            jTextField8.setText("jTextField8");

            jTextField9.setText("jTextField9");

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextField6))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField8)
                                .addComponent(jTextField7)))))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("OTP/SMS - токен"));
            jPanel3.setMaximumSize(new java.awt.Dimension(217, 139));
            jPanel3.setMinimumSize(new java.awt.Dimension(217, 139));
            jPanel3.setName(""); // NOI18N

            jLabel7.setText("Модель:");

            jLabel8.setText("Заводской номер:");

            jLabel9.setText("Дата выдачи:");

            jLabel10.setText("Сумма подтверждения:");

            jTextField10.setText("jTextField10");

            jTextField11.setText("jTextField11");

            jTextField12.setText("jTextField12");

            jTextField13.setText("jTextField13");

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jLabel10)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jLabel7)
                    .addGap(36, 36, 36)
                    .addComponent(jTextField10))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8))
                    .addGap(24, 24, 24)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField12)
                        .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.TRAILING)))
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jTextField1.setEditable(false);
            jTextField1.setText("ICUSNUM");

            jTextField2.setEditable(false);
            jTextField2.setText("CUSFIO");

            jTextField3.setEditable(false);
            jTextField3.setText("CUSPOST");

            jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel11.setText("Выберите запись в которой присутствует выданное ранее оборудование.");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jButton2)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1))
                        .addComponent(jScrollPane1))
                    .addContainerGap())
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addGap(96, 96, 96))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel11)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addContainerGap())
            );

            pack();
        }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //DialogInsert2.YES=1;
        this.dispose();        
    }//GEN-LAST:event_jButton1ActionPerformed


/*КНОПКА СОХРАНИТЬ*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ReturnToParent();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public  void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogInsert3s.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                   ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogInsert3s.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                   ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogInsert3s.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                   ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogInsert3s.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                   ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogInsert3s dialog = new DialogInsert3s(new javax.swing.JDialog(),"Ранее выданные ПО и оборудование", true, icusnum, Integer.toString(clinum), reasonflag);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables



    public void refilltable(JTable table) throws SQLException {
        String sqlpost="";
        
        if (reasonflag==1){
            sqlpost="";//" and cfacename1 like '%"+cusF+"%' and cfacename2 like '%"+cusI+"%' and cfacename3 like '%"+cusO+"%'";
        }
        
/*        try {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }        */        

        cleartable(table);
        Connection con = FrameLogon.mainpool.OpenConnection();//DriverManager.getConnection(Frame1.get_dbconndata(1), Frame1.get_dbconndata(2), Frame1.get_dbconndata(3));
        Statement st = con.createStatement();        
        ResultSet rs = st.executeQuery("select " +         
        "   ikeynum   IKEYNUM" + 
        "   ,to_char(dregdate,'DD.MM.RRRR')  REGDATE" + 
        "   ,cfacename1||' '||cfacename2||' '||cfacename3   NAME" + 
        "   ,cfacepost  POST" + 
        "   ,ctkntype USBTYPE" + 
        "   ,ctknid  USBID" + 
        "   ,itknjnum USBNUM" + 
        "   ,idsttknnum USBACTNUM" + 
        "   ,to_char(ddsttnkd,'DD.MM.RRRR') USBACTDATE" +   //8
        "   ,nvl(ccnfrmtype,'NULL') OTPTYPE" + 
        "   ,nvl(ccnfrmid,'NULL')  OTPID" + 
        "   ,icnfrmjnum OTPNUM" + 
        "   ,nvl(icnfrmsum,0) OTPSUM" + 
        "   ,idistnum DISTNUM" + 
        "   ,to_char(ddist,'DD.MM.RRRR') DISTDATE" + 
        "    " + 
        "from xxi.key_info where iclicusid="+Integer.toString(this.icusnum)+sqlpost+" order by ikeynum");
               
        table.setModel(buildTableModel(rs)); 
        setColumnsWidth(jTable1);
        rs.close();
        st.close();
        con.close(); 
        con = null;
        FrameLogon.mainpool.Close();    
    }

        public void cleartable(JTable table) {
            DefaultTableModel model = (DefaultTableModel)table.getModel();
            while (model.getRowCount() > 0){
                    for (int i = 0; i < model.getRowCount(); ++i){
                        model.removeRow(i);
                    }
                };            
        }

        public void FillFormData() {
            //System.out.println(jTable1.getSelectedRow());
            String text;
            if(jTable1.getSelectedRow() != -1){
            this.jTextField1.setText(Integer.toString(this.clinum));
            if(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString().length()>0)this.jTextField2.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
            else jTextField2.setText("");
            if(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString().length()>0)this.jTextField3.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
            else jTextField3.setText("");
            if(jTable1.getValueAt(jTable1.getSelectedRow(), 13).toString().length()>0)this.jTextField4.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 13).toString());
            else jTextField4.setText("");
            if(jTable1.getValueAt(jTable1.getSelectedRow(), 14).toString().length()>0)this.jTextField5.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 14).toString());
            else jTextField5.setText("");
            if(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString().length()>0)this.jTextField6.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
            else jTextField6.setText("");           
            if(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString().length()>0)this.jTextField7.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
            else jTextField7.setText("");            
            if(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString().length()>0)this.jTextField8.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
            else jTextField8.setText("");            
            if(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString().length()>0)this.jTextField9.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
            else jTextField9.setText("");            
            if(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString().length()>0)this.jTextField10.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
            else jTextField10.setText("");            
            if(jTable1.getValueAt(jTable1.getSelectedRow(), 10).toString().length()>0)this.jTextField11.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 10).toString());
            else jTextField11.setText("");
            
            if(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString().length()>0)this.jTextField12.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
            else jTextField12.setText("");
            if(jTable1.getValueAt(jTable1.getSelectedRow(), 12).toString().length()>0)this.jTextField13.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 12).toString());
            else jTextField13.setText("");
            
            }
            
        }
    
    public void ReturnToParent() {
        //System.out.println(jTable1.getSelectedRow());
        if(jTable1.getSelectedRow() != -1){            
            DialogInsert2.gikeynum=jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            DialogInsert2.gregdate=jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
            DialogInsert2.gcliname=jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
            DialogInsert2.gpost=jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
            DialogInsert2.gusbtype=jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString();
            DialogInsert2.gusbid=jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString();
            DialogInsert2.gusbnum=jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString();
            DialogInsert2.gusbactnum=jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString();
            DialogInsert2.gusbactdate=jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString();
            DialogInsert2.gotptype=jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString();
            DialogInsert2.gotpid=jTable1.getValueAt(jTable1.getSelectedRow(), 10).toString();
            DialogInsert2.gotpnum=jTable1.getValueAt(jTable1.getSelectedRow(), 11).toString();
            DialogInsert2.gotpsum=jTable1.getValueAt(jTable1.getSelectedRow(), 12).toString();
            DialogInsert2.gdistnum=jTable1.getValueAt(jTable1.getSelectedRow(), 13).toString();
            DialogInsert2.gdistdate=jTable1.getValueAt(jTable1.getSelectedRow(), 14).toString();                
            if (reasonflag==1){
                DialogInsert2.linkdata=1; //Сообщаем родительской форме о том что данные по оборудованию нужно привязать к существующей записи журнала.    
            }else if (reasonflag==2){
                DialogInsert2.linkdataotp=1; //Сообщаем родительской форме о том что данные по оборудованию нужно привязать к существующей записи журнала.    
            }
            
        }        
    }        
        
    

    public void FillFormDataLocal() {            
        this.jTextField1.setText(Integer.toString(this.clinum));
        this.jTextField2.setText(this.cliname);
        this.jTextField3.setText(this.post);
        this.jTextField4.setText(this.distnum);
        this.jTextField5.setText(this.distdate);
        this.jTextField6.setText(this.usbtype);
        this.jTextField7.setText(this.usbid);
        this.jTextField8.setText(this.usbactdate);
        this.jTextField9.setText(this.usbnum);
        this.jTextField10.setText(this.otptype);
        this.jTextField11.setText(this.otpid);
        this.jTextField12.setText(this.otpnum);
        this.jTextField13.setText(this.otpsum);        
    }   
    
    public void GetCusFIO(String ownerid) throws SQLException
    {
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
               
        String sql_f="select regexp_replace(CCUSNAME,' (.*)') as v01 from xxi.cus where icusnum = "+ownerid; //фамилия
        String sql_i="select regexp_replace(CCUSNAME, ' (.*)|^[^ ]* ') as v01 from xxi.cus where icusnum = "+ownerid; //имя      
        String sql_o="select regexp_replace(CCUSNAME,'(.*) ') as v01 from xxi.cus where icusnum = "+ownerid; //отчество
        
        Connection con = FrameLogon.mainpool.OpenConnection(); //DriverManager.getConnection(Frame1.get_dbconndata(1), Frame1.get_dbconndata(2), Frame1.get_dbconndata(3));
        Statement st = con.createStatement();
    
        ResultSet resultSet = st.executeQuery(sql_f);        
        while (resultSet.next()) 
          {
             cusF=resultSet.getString("v01");
             //System.out.println(sql_f);
          }
        resultSet = st.executeQuery(sql_i);
        while (resultSet.next()) 
          {
             cusI=resultSet.getString("v01");
          }
        resultSet = st.executeQuery(sql_o);
        while (resultSet.next()) 
          {
             cusO=resultSet.getString("v01");
          }

        resultSet.close();
        st.close();
        con.close(); 
        con = null;
        FrameLogon.mainpool.Close();

    }
    
    public static DefaultTableModel buildTableModel(ResultSet rs) throws SQLException {
        ResultSetMetaData metaData = rs.getMetaData();
        // names of columns
        String[] ColNames = {
                                "ID"                                
                                ,"ВЫДАН      "
                                ,"ИМЯ КЛИЕНТА                      "
                                ,"ДОЛЖНОСТЬ       "
                                ,"НЭК ТИП                  "
                                ,"НЭК S/N              "
                                ,"НЭК УЧ.№"
                                ,"НЭК АКТ"
                                ,"ДАТА ВЫДАЧИ"
                                ,"OTP ТИП                  "
                                ,"OTP S/N       "
                                ,"OTP УЧ.№"
                                ,"OTP СУММА"
                                ,"ДИСТР. №"
                                ,"ДАТА ВЫДАЧИ"
                             };
        // names of columns
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 0; column <= columnCount-1; column++) {
            //columnNames.add(metaData.getColumnName(column));
            columnNames.add(ColNames[column]);
        }

        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }
        
        TableModel resmodel = new DefaultTableModel(data, columnNames) {
              public boolean isCellEditable(int rowIndex, int mColIndex) {
                return false;
              }
            };
        
        return (DefaultTableModel) resmodel;
    }
    

    /*Формат таблицы по ширине названия столбца*/
        public void setColumnsWidth(JTable table) {
            table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            JTableHeader th = table.getTableHeader();
            for (int i = 0; i < table.getColumnCount(); i++) {
                TableColumn column = table.getColumnModel().getColumn(i);
                int prefWidth = 
                    Math.round(
                        (float) th.getFontMetrics(
                            th.getFont()).getStringBounds(th.getTable().getColumnName(i),
                            th.getGraphics()
                        ).getWidth()
                    );
                column.setPreferredWidth(prefWidth + 10);
            }
        }
  
  
}
