

  CREATE TABLE "XXI"."KEY_INFO" 
   (	"IKEYNUM" NUMBER(12,0) NOT NULL ENABLE, 
	"INPP" NUMBER(12,0) NOT NULL ENABLE, 
	"DREGDATE" DATE, 
	"CRGEVENT" VARCHAR2(500), 
	"ICLICUSID" NUMBER(12,0) NOT NULL ENABLE, 
	"CCLINAME" VARCHAR2(500), 
	"CSGNID" VARCHAR2(500), 
	"IFACECUSID" NUMBER(12,0), 
	"CFACENAME1" VARCHAR2(500), 
	"CFACENAME2" VARCHAR2(500), 
	"CFACENAME3" VARCHAR2(500), 
	"CFACEPOST" VARCHAR2(100), 
	"CTKNTYPE" VARCHAR2(100), 
	"CTKNID" VARCHAR2(100), 
	"ITKNJNUM" NUMBER(6,0) NOT NULL ENABLE, 
	"CCNFRMTYPE" VARCHAR2(100), 
	"CCNFRMID" VARCHAR2(100), 
	"ICNFRMJNUM" NUMBER(6,0) DEFAULT NULL, 
	"ICNFRMSUM" NUMBER(12,0), 
	"IDISTNUM" NUMBER(6,0) DEFAULT NULL, 
	"DDIST" DATE, 
	"IPROTONUM" NUMBER(6,0) NOT NULL ENABLE, 
	"IDSTTKNNUM" NUMBER(6,0) NOT NULL ENABLE, 
	"DDSTTNKD" DATE, 
	"ILKEYNUM" NUMBER(12,0) DEFAULT NULL, 
	"ILDSTTKNNUM" NUMBER(6,0) DEFAULT NULL, 
	"DLDSTTNKD" DATE DEFAULT NULL, 
	"ILTKNJNUM" NUMBER(6,0) DEFAULT NULL, 
	"ILKEYNUMOTP" NUMBER(12,0) DEFAULT NULL, 
	"ILDACTOTP" NUMBER(6,0) DEFAULT NULL, 
	"DLDACTOTP" DATE DEFAULT NULL, 
	"IDSTSGNNUM" NUMBER(6,0) NOT NULL ENABLE, 
	"DDSTSGND" DATE, 
	"IPRODNUM" NUMBER(6,0) NOT NULL ENABLE, 
	"DPRODD" DATE, 
	"IWIPENUM" NUMBER(6,0) DEFAULT NULL, 
	"DWIPED" DATE DEFAULT NULL, 
	"CCOMMENT" VARCHAR2(1024) DEFAULT NULL, 
	"IJRNKI" NUMBER(7,0) NOT NULL ENABLE, 
	"IJRNKIOTP" NUMBER(7,0), 
	"IJRNKIDIST" NUMBER(7,0), 
	 CONSTRAINT "KEYINFO_PK" PRIMARY KEY ("IKEYNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "UQ_KEYINFO" UNIQUE ("IKEYNUM", "INPP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "XXI"."KEY_INFO"."IKEYNUM" IS 'ID записи';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."INPP" IS 'Порядковый номер журнала';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."DREGDATE" IS 'Дата выдачи ключа';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."CRGEVENT" IS 'Причина:(1) - Первичная регистрация;(2) - Компрометация;(3) - Смена должностного лица;(4) - Плановая смена ключа';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."ICLICUSID" IS 'ID клиента (внутр. CUS)';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."CCLINAME" IS 'Полное наименование предприятия';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."CSGNID" IS 'ID ключа ЭП';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."IFACECUSID" IS 'ID владельца ключа (CUS)';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."CFACENAME1" IS 'Фамилия владельца ЭП';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."CFACENAME2" IS 'Имя владельца ЭП';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."CFACENAME3" IS 'Отчество владельца ЭП';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."CFACEPOST" IS 'Должность владельца ЭП';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."CTKNTYPE" IS 'Тип носителя (usb-token)';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."CTKNID" IS 'S/N носителя';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."ITKNJNUM" IS 'Учётный номер носителя';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."CCNFRMTYPE" IS 'Тип средства подтверждения (otp-токен)';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."CCNFRMID" IS 's/n средства подтверждения (otp-токен)';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."ICNFRMJNUM" IS 'Учётный номер средства подтверждения';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."ICNFRMSUM" IS 'Сумма подтверждения OTP-токена';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."IDISTNUM" IS 'Учётный номер дистрибутива (установочный пакет)';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."DDIST" IS 'дата выдачи дистрибутива';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."IPROTONUM" IS 'Номер Протокола и Заключения';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."IDSTTKNNUM" IS '№ Акта передачи носителя';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."DDSTTNKD" IS 'Дата акта передачи носителя';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."ILKEYNUM" IS 'ID записи (связь с другой строкой журнала)';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."ILDSTTKNNUM" IS '№ Акта передачи носителя (из связанной строки ILNKIKN)';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."DLDSTTNKD" IS 'Дата акта передачи носителя (из связанной строки ILNKIKN)';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."ILTKNJNUM" IS 'Учётный номер носителя (из связанной строки ILNKIKN)';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."ILKEYNUMOTP" IS 'ID записи (связь с другой строкой журнала)';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."ILDACTOTP" IS '№ Акта передачи носителя в которм был передан OTP(из связанной строки ILKEYNUMOTP)';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."DLDACTOTP" IS 'Дата акта передачи носителя в котором передавался OTP (из связанной строки ILKEYNUMOTP)';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."IDSTSGNNUM" IS '№ Акта пердачи ключа ЭП';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."DDSTSGND" IS 'Дата акта передачи ключа ЭП';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."IPRODNUM" IS '№ Акта ввода в эксплуатацию';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."DPRODD" IS 'Дата акта ввода в эксплуатацию';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."IWIPENUM" IS '№ Акта уничтожения';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."DWIPED" IS 'Дата акта уничтожения';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."CCOMMENT" IS 'Примечание';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."IJRNKI" IS 'Привязка строки к журналу для USB токена';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."IJRNKIOTP" IS 'Привязка строки к журналу для OTP токена';
   COMMENT ON COLUMN "XXI"."KEY_INFO"."IJRNKIDIST" IS 'Привязка строки к журналу для дистрибутив';
   COMMENT ON TABLE "XXI"."KEY_INFO"  IS 'Журнал учета ключевой информации (ДБО)';
