

  CREATE TABLE "XXI"."KEY_CERT" 
   (	"ICRTKEYNUM" NUMBER(12,0) NOT NULL ENABLE, 
	"ICEYNUM" NUMBER(12,0) NOT NULL ENABLE, 
	"CKEYID" VARCHAR2(500), 
	"CSKZITYPE" VARCHAR2(500), 
	"DREGDATE" DATE, 
	"DSTARTD" DATE, 
	"DENDD" DATE, 
	"CSIGNGRP" VARCHAR2(500), 
	"ISTATE" NUMBER(6,0) DEFAULT 1, 
	"IWIPENUM" NUMBER(6,0) DEFAULT NULL, 
	"DWIPED" DATE DEFAULT NULL, 
	"CCOMMENT" VARCHAR2(1024) DEFAULT NULL, 
	"IJRNKC" NUMBER(7,0) NOT NULL ENABLE, 
	 CONSTRAINT "KEYCERT_PK" PRIMARY KEY ("ICRTKEYNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "UQ_KEYCERT" UNIQUE ("ICRTKEYNUM", "ICEYNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "XXI"."KEY_CERT"."ICRTKEYNUM" IS 'ID записи';
   COMMENT ON COLUMN "XXI"."KEY_CERT"."ICEYNUM" IS 'ID записи в таблцие key_info';
   COMMENT ON COLUMN "XXI"."KEY_CERT"."CKEYID" IS 'ID ключа ЭП';
   COMMENT ON COLUMN "XXI"."KEY_CERT"."CSKZITYPE" IS 'Тип СКЗИ';
   COMMENT ON COLUMN "XXI"."KEY_CERT"."DREGDATE" IS 'Дата регистрации ключа';
   COMMENT ON COLUMN "XXI"."KEY_CERT"."DSTARTD" IS 'Дата начала действия';
   COMMENT ON COLUMN "XXI"."KEY_CERT"."DENDD" IS 'Дата окончания действия';
   COMMENT ON COLUMN "XXI"."KEY_CERT"."CSIGNGRP" IS 'Группа подписи';
   COMMENT ON COLUMN "XXI"."KEY_CERT"."ISTATE" IS 'Статус ключа: 1 действует, 2 уничтожен';
   COMMENT ON COLUMN "XXI"."KEY_CERT"."IWIPENUM" IS '№ Акта уничтожения';
   COMMENT ON COLUMN "XXI"."KEY_CERT"."DWIPED" IS 'Дата акта уничтожения';
   COMMENT ON COLUMN "XXI"."KEY_CERT"."CCOMMENT" IS 'Примечание';
   COMMENT ON COLUMN "XXI"."KEY_CERT"."IJRNKC" IS 'Привязка сертификата к журналу';
   COMMENT ON TABLE "XXI"."KEY_CERT"  IS 'Сертификаты пользователей (ДБО)';
